### ISSUE TITLE
Do not use buffer, if not required

### ISSUE THREAD

**Issue by blaubaer** [dtgorski/jsonlex#4]
First of all: Thanks for this lean and efficient project. 🙂

---

### Payload example
> ℹ️ Used for the following explanations
 ```json
 {
     "elementA": {
        "payload": {
           "propA": 1,
           "propB": true,
        },
        "type": "foo"
     },
     "elementB": {
        "something": "great"
     }
 }
 ```

### Assumitions

1. You have a _very_ huge JSON file which you don't want to buffer fully in the memory (for example more than 4GB). Caused by this you want to parse this file (obviously) step by step.

2. You sometimes have to read a element (which it's children) 2 times.

   In the following example, we want to read the `elementA` 2 times. The first time we want to read everything, until we find the sub element `type`. Based on this we can decide how the deal with the rest of the content and rewind something which we buffered a moment ago and start over again (but ignoring the sub element `type` this time).
   > ℹ️ In JSON there is no guarantee for the order of elements inside of an object. As this are objects which are accepted via REST interface, it might be hard to explain the users of this REST API that this order is important. On top of that several JSON serialization libraries haven no possibility to force an order.

### Pseudocode of processing
```golang
var r myRewindableReader // implements io.Reader

// ... object key `elementA` (jsonlex.TokenSTR) found
// ... expected token jsonlex.TokenCOL found

// ... expect token jsonlex.TokenLCB
r.StartBuffering()
var type string
for {
    // ... expect key element (jsonlex.TokenSTR)
    // ... expect token jsonlex.TokenCOL
    if key == "type" {
        type = token.String()
    } else {
        // ... skip the whole sub element
        // in this case `"payload": { ... }`
    }
    // expect next token
    switch token.Kind {
       case jsonlex.TokenCOM:
           continue
       case jsonlex.TokenLCB:
           break
       default:
           panic("unexpected")
    }
}
r.RewindBuffer()
contentDeserializer = contentDeserializers.GetByType(type)
contentDeserializer.Deserialize(r) // ... we'll parse the whole element content again
                                   // in this case `"payload": { ... }`
```

### The actual issue
`jsonlex.Lexer` consumes in this example always also the tailing `,` (if the element was consumed fully) and stores it inside of `jsonlex.Lexer.buf` altough it was not already consumed or might be important for the current parsed element (in this case `jsonlex.TokenCOM` was already consumed while parsing `jsonlex.TokenLCB`).

As I result on the original reader everything as `[..] "payload": { [...] },` was already consumed. As I only would expect that `[..] "payload": { [...] }`  (without the tailing `,`) my `myRewindableReader` has to implement a lot of very complicated logic to foresee if this `,` was already consumed or not. Also caused by this I cannot simply can use the same instance of `jsonlex.Lexer`, I have to create a new instance of it, which does not has this buffered instance stored.

This whole scenario gets just more and more complicated if I have to do those scenarios also recursively.

Can we somehow change the behavior that `jsonlex.Lexer.buf` is not pre-consumed if a token was successfully parsed?

**Comment by dtgorski** [comment]
Hey Gregor,

could you please write a small but sufficient test, that covers the issue and what you would expect, and push it? I would use it as verification, that I understood the problem correctly. You can use the *issue-4* branch for this. Thank you in advance, dtg

**Comment by blaubaer** [comment]
Hey @dtgorski, please see the MR #5. I've created on the one hand a test for that and on the other hand also drafted a proposal to deal with that.

**Comment by dtgorski** [comment]
In your use case, Gregor, do you use `jsonlex.Cursor` or `jsonlex.Lexer` (the latter with a customized callback function) to interate over the stream?

* The `Cursor` reads indeed one byte ahead, which it needs to satisfy a `Peek()` functionality. It also can utilize a token Filter, to e.g. skip all colons and commas completely.
* Directly using the `Lexer` (which is used by the `Cursor` under the hood), outputs all the tokens as they appear in the stream, does not consume ahead, so that if something has been read from the stream already, it is likely that custom/your code consumed it.

If it's the `Cursor`, then maybe I should check out if an `Unread()` function on the `Cursor` (unread (one) token on the stream) is feasible.

**Comment by blaubaer** [comment]
I indeed used the `jsonlex.Lexer` directly. In case of literals, `,`, `:`, `[`, `]`, `{` and `}`. It was also always reading one ahead. I was able to fix that for everything (except the literals) and for the literals I was implementing in my PR the `UnreadByte()` method, which is provided by some other readers, such as `bytes.Buffer` (for example).

**Comment by blaubaer** [comment]
@dtgorski Any updates on this?

**Comment by dtgorski** [comment]
First, Gregor, thank you for the reminder. Things tend to get buried due to daily business.

In one of my earlier comments, I suggested providing a test for the behaviour which you described. I was of course
hoping for a test against the current _jsonlex_ code :), because you claimed that the lexer was consuming ahead, which
you did not expect, and I thought it could be an error in the current implementation. A test against your changes did
not help me very much here :)

Assumption:

Now a few days later and at a second glance on the problem, I basically doubt that having a rewindable reader is the correct solution to your requirements, except the reader is really seekable (like having Seeker interface) and is aware of the complete stream content so far (which I doubt as well). It is likely that you, soon or later, run into a buffer "underflow" when you are trying to rewind, because the underlying buffer has been updated with new data,  while trying to skip the "payload" to reach the "type" key.

If it is the case, I would solve this by copying the "payload" content to a different buffer on the fly (leveraging a sync.Pool should be very efficient in terms of avoiding garbage collection from heap), on which you could eventually run a separate Decoder (or Lexer), when you know the "type". Maybe this could solve you "need unread a byte" problem as well.

If it is not the case, forget what I wrote.

And here we are, the unread byte thing. I am still not convinced, that something has to be done to the _jsonlex_.Lexer
because a byte is allegedly read ahead: each time the yield function is invoked, you get one token. When you are trying to lex an object in curly braces, you must not stop on a trailing comma after this object, but one token earlier, on the closing curly brace. In this case, after returning to your main function, you would get the comma token (if it exists, ofc) next.

Alas, I need to guess, what your content deserializer is doing, and why it apparently consumes more than it should.
Maybe you can provide a small working example with the complete code, including an exemplary deserializer?

**Comment by blaubaer** [comment]
Hi @dtgorski,

it is hard for me to give you the whole code, because I build this into a complex scenario, where it might be hard to point out the real issue. On the other hand I don't know how I should explain it better as with my initial message (of this ticket). It might help to have a look at the following tests of my PR: 
1. [`lexer_test.go#371`](https://github.com/dtgorski/jsonlex/pull/5/files#diff-d8950dc0d3931a7b1b6bebcfc7e69a626e273f98ecae24a596e5f90b29c4d7b0R371)
2. [`lexer_test.go#435`](https://github.com/dtgorski/jsonlex/pull/5/files#diff-d8950dc0d3931a7b1b6bebcfc7e69a626e273f98ecae24a596e5f90b29c4d7b0R435)

Please run both tests but replace this lines:
```golang
l := NewLexer(y, LexerOptEnableUnreadBuffer)
```
with the following line to disable the unread feature:
```golang
l := NewLexer(y)
```

This will lead to test errors like this:
```
    [..]
    lexer_test.go:365: 7: uexpected left content to parse (12 != 13) " \"b\": false}"
    lexer_test.go:365: 11: uexpected left content to parse (0 != 1) ""
    [..]
```
In all of this cases you can see that always one byte is missing. My PR enables this `LexerOptEnableUnreadBuffer`-feature and lead to that those important bytes are unread afterwards and the tests are working.

BTW: This feature of `UnreadByte() error` is in general supported by other `io.Reader` implementing structs like:
1. [`bytes.Buffer.UnreadByte()`](https://github.com/golang/go/blob/master/src/bytes/buffer.go#L392)
2. [`bufio.Reader.UnreadByte()`](https://github.com/golang/go/blob/master/src/bufio/bufio.go#L272)
3. [..]

What all of them have in common: They only unread maximum of one byte. And this mechanism is supported by various of parsers (of the Golang SDK), like:
1. [`math/big.scanSign(..)` by `math/big.Int.Scan(..)`](https://github.com/golang/go/blob/master/src/math/big/intconv.go#L210)
2. [`net/textproto.Reader.skipSpace()` by `net/textproto.Reader.ReadContinuedLineBytes()`](https://github.com/golang/go/blob/master/src/net/textproto/reader.go#L183)
3. [..]

That means this is a normal behavior of good parser implementations of Go. 😉

**Comment by dtgorski** [comment]
Indeed, there is a bug in the current jsonlex implementation and your solution works good around it.

I am just asking myself, if it would be "better" to replace the jsonlex.Scan(io.Reader) with jsonlex.Scan(io.ByteScanner) [1] to enforce the existence of an UnreadByte function, so the internals of the scanner can "unread" transparently without extra lexer configuration.

I know, this would break the API as is, because I would prefer not to introduce a V2 version. jsonlex is sparingly used in the wild, and I have only two implementations working for my own.

What do you think? Change the function signature?

[1] https://pkg.go.dev/io#ByteScanner

**Comment by blaubaer** [comment]
Generally I would say not everybody needs this feature and I would also not call it a bug 🙂. To require `io.ByteScanner` instead of the simple one `io.Reader` makes it more restrictive. I would leave the interface as it is and leave this feature optional.

**Comment by dtgorski** [comment]
A version v0.4.0 should be available soon via the Go proxies. It contains your changes plus a few cosmetic modifications.

It would be very nice, if you could ensure that this version works for you correctly and close this ticket.

Thank you for your patience, Gregor.

**Comment by blaubaer** [comment]
Tested and works like charm. Thank you so much. 🙂

I assume this ticket as solved.
